### ISSUE TITLE
Plugin panics on JeffersonPass system

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap-plugin-collector-intel-dcm-platform#3]
## StackTrace
```
DEBU[2016-11-21T20:21:26-08:00] Recover from panic: runtime error: index out of range  _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00]                                               _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00] Stack of 4096 bytes: goroutine 10 [running]:  _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00] github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/vendor/github.com/intelsdi-x/snap/control/plugin.catchPluginPanic(0xc420012c30)  _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00]         /home/jrcookli/.gvm/pkgsets/go1.7.1/snap/src/github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/vendor/github.com/intelsdi-x/snap/control/plugin/plugin_deprecated.go:242 +0xc1  _module=plugin-exec io=stderr plugin=snap-p
lugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00] panic(0x75a4c0, 0xc420010110)                 _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00]         /home/jrcookli/.gvm/gos/go1.7.1/src/runtime/panic.go:458 +0x243  _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00] github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/ipmi.(*SdrParser).GetSdrBytes(0xc42044cfb0, 0xc42015d038, 0x2, 0x2, 0x1000050000, 0xc420011e96, 0x6, 0xc42044c960, 0x410868, 0x0, ...)  _module=plugin-exec io=stderr plugin=snap
-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00]         /home/jrcookli/.gvm/pkgsets/go1.7.1/snap/src/github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/ipmi/sdr.go:371 +0x217  _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00] github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/ipmi.(*SdrParser).GetSdrHeader(0xc42044cfb0, 0xc42015d038, 0x2, 0x2, 0x0, 0xc420011e96, 0x6, 0x4b78c7, 0xc4204ae370, 0xb66012)  _module=plugin-exec io=stderr plugin=snap-plugin-
collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00]         /home/jrcookli/.gvm/pkgsets/go1.7.1/snap/src/github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/ipmi/sdr.go:380 +0xba  _module=plugin-exec io=stderr plugin=snap-plugin-collector-intel-dcm-platform
DEBU[2016-11-21T20:21:26-08:00] github.com/intelsdi-x/snap-plugin-collector-intel-dcm-platform/ipmi.(*SdrParser).ScanSdrLoop(0xc42044cfb0, 0xc42015d038, 0x2, 0x2, 0x100000, 0xc420011e96, 0x6, 0x0, 0x0, 0x0, ...)  _module=plugin-exec io=stderr plugin=snap-plugin-collector-
intel-dcm-platform
```

## node manager version
```
 root@jp22-4:~# ipmi-oem intelnm get-node-manager-version
Node Manager Version   : 03h
IPMI Interface Version : 02h
Patch Version          : 0
Firmware Revision      : 2.17
```
## bmc-info
```
root@jp22-4:~# bmc-info
Device ID             : 33
Device Revision       : 1
Device SDRs           : unsupported
Firmware Revision     : 1.17
Device Available      : yes (normal operation)
IPMI Version          : 2.0
Sensor Device         : supported
SDR Repository Device : supported
SEL Device            : supported
FRU Inventory Device  : supported
IPMB Event Receiver   : supported
IPMB Event Generator  : supported
Bridge                : unsupported
Chassis Device        : supported
Manufacturer ID       : Intel Corporation (343)
Product ID            : 77
Auxiliary Firmware Revision Information : 10371701h

GUID : 00000000-0000-0000-0000-0000434d4249

System Firmware Version       : rsion1.0
System Name                   : Manager
Primary Operating System Name : SE Server 1.0
Operating System Name         :

Channel Information

Channel Number       : 0
Medium Type          : IPMB (I2C)
Protocol Type        : IPMB-1.0
Active Session Count : 0
Session Support      : session-less
Vendor ID            : Intelligent Platform Management Interface forum (7154)

Channel Number       : 1
Medium Type          : 802.3 LAN
Protocol Type        : IPMB-1.0
Active Session Count : 0
Session Support      : multi-session
Vendor ID            : Intelligent Platform Management Interface forum (7154)

Channel Number       : 2
Medium Type          : 802.3 LAN
Protocol Type        : IPMB-1.0
Active Session Count : 0
Session Support      : multi-session
Vendor ID            : Intelligent Platform Management Interface forum (7154)

Channel Number       : 3
Medium Type          : 802.3 LAN
Protocol Type        : IPMB-1.0
Active Session Count : 0
Session Support      : multi-session
Vendor ID            : Intelligent Platform Management Interface forum (7154)

Channel Number       : 6
Medium Type          : IPMB (I2C)
Protocol Type        : IPMB-1.0
Active Session Count : 0
Session Support      : session-less
Vendor ID            : Intelligent Platform Management Interface forum (7154)

Channel Number       : 7
Medium Type          : System Interface (KCS, SMIC, or BT)
Protocol Type        : KCS
Active Session Count : 0
```

## dmi-decode
```
# dmidecode 2.12
SMBIOS 2.6 present.
157 structures occupying 9641 bytes.
Table at 0x000E9850.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
        Vendor: Intel Corp.
        Version: SE5C600.86B.01.08.0003.022620131521
        Release Date: 02/26/2013
        Address: 0xF0000
        Runtime Size: 64 kB
        ROM Size: 8192 kB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                BIOS shadowing is allowed
                Boot from CD is supported
                Selectable boot is supported
                EDD is supported
                5.25"/1.2 MB floppy services are supported (int 13h)
                3.5"/720 kB floppy services are supported (int 13h)
                3.5"/2.88 MB floppy services are supported (int 13h)
                Print screen service is supported (int 5h)
                8042 keyboard services are supported (int 9h)
                Serial services are supported (int 14h)
                Printer services are supported (int 17h)
                ACPI is supported
                USB legacy is supported
                BIOS boot specification is supported
                Targeted content distribution is supported
        BIOS Revision: 4.6

Handle 0x0001, DMI type 1, 27 bytes
System Information
        Manufacturer: Intel Corporation
        Product Name: S2600JF ..........
        Version: ....................
        Serial Number: ............
        UUID: 8163803B-87B4-E111-B70D-001E674FBBDA
        Wake-up Type: Power Switch
        SKU Number: To be filled by O.E.M.
        Family: To be filled by O.E.M.

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
        Manufacturer: Intel Corporation
        Product Name: S2600JF
        Version: G28033-506
        Serial Number: QSJP22406291
        Asset Tag: ....................
        Features:
                Board is a hosting board
                Board is replaceable
        Location In Chassis: To be filled by O.E.M.
        Chassis Handle: 0x0003
        Type: Motherboard
        Contained Object Handles: 0
```

cc: @dancyding

**Comment by WangJialei-A** [comment]
pull #10 has already fixed the out of range issue.
